language: node_js
node_js:
- node
- '6'
script: npm run test-ci
deploy:
  provider: npm
  email: christopher.andrejewski@gmail.com
  api_key:
    secure: V5lOu9128tq70l5ps3tQHXxNBuzeebhQY1dd6wbh8nTqXhBuaG7y0H0X0sadHWRr89UI5tIMD6Ka9C5V/dRpT51CIGW3alFwoJldPscM5Hn2gRTy3x98wlGdMI9waOrputhqKERC1PE5MouYpNNawTkg6YnpB4GZycrgKNEqbn16DJop0DZ9bIYnVQq4M9gTHkVRN+NIV2DUepVvYB+hUDU038MnSNLcHBDvEO2YakgC4EbF9M5y2FNdye+0/qaQaNyYX03w9mF3p302StZUKgEzCGpzN+9zaTA3058FTgNmMWx2s3exnkhABHhyxlAL20VzaGbYLUqsUVLipDUm+Tlhocmw0pM3hvA2zgnPJmrSFeSiuIT+GbOUOPGLpiRPdXncXmxGWgbVZ27iY3uvKcBbJvyRkhOJyPhIrJHB6lmmG+Wm7NyRZN7k+A5MFqtrKGrPxUbJCFJW6n1eIIBf+aJBHHHXFkLQ4P94y9lHsmgGI8ezngH0La7xHwwVemQz46onhONvVzMYf4E6pGHmZU59sQ7bSEBY175Ra7jmflPhwCrCcgp6vFRv8/bAScAsbYcMBins7ga6+8llM1xNPinRDuNnlh9E64EmFDPBFEK37jvFuOv5ohGIsXFjc2JDnq3M8Q8fHVC4ALKlmP5umTbg/6QqfuUXw1nMsHtcWBE=
  on:
    tags: true
    repo: andrejewski/please-update
after_success:
- npm run coveralls
